apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-conf
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          readOnly: true
          name: index-html

      volumes:
      - name: nginx-conf
        configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      - name: index-html
        configMap:
            name: index-html
            items:
              - key: index.html
                path: index.html
